import { Professional, User, Service, ServiceCategory } from '../types';

export const MOCK_BARBERS: (Professional & { user: User })[] = [
  {
    id: '1',
    userId: 'u1',
    bio: 'Specialist in low fades and traditional Nigerian hairstyles. Over 5 years of experience in Lagos.',
    categories: ['Barbers', 'Grooming'],
    yearsExperience: 5,
    serviceMode: 'both',
    address: 'Lekki Phase 1, Lagos',
    latitude: 6.5244,
    longitude: 3.3792,
    avgRating: 4.8,
    totalReviews: 124,
    isAvailable: true,
    hasOffer: true,
    accountNumber: '0123456789',
    bankName: 'GT BANK',
    user: {
      id: 'u1',
      fullName: 'Boluwatife Adeyemi',
      email: 'bolu@example.com',
      phone: '08012345678',
      role: 'professional',
      isVerified: true,
      verificationStatus: 'verified',
      createdAt: new Date(),
      updatedAt: new Date(),
      avatarUrl: 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?q=80&w=400&auto=format&fit=crop'
    }
  },
  {
    id: '2',
    userId: 'u2',
    bio: 'Professional female hair stylist focusing on braids and weaves. I offer home visit services.',
    categories: ['Braiders', 'Stylists'],
    yearsExperience: 3,
    serviceMode: 'home_visit',
    address: 'Victoria Island, Lagos',
    latitude: 6.4281,
    longitude: 3.4219,
    avgRating: 4.9,
    totalReviews: 56,
    isAvailable: true,
    user: {
      id: 'u2',
      fullName: 'Chinwe Okeke',
      email: 'chinwe@example.com',
      phone: '08087654321',
      role: 'professional',
      isVerified: true,
      verificationStatus: 'verified',
      createdAt: new Date(),
      updatedAt: new Date(),
      avatarUrl: 'https://images.unsplash.com/photo-1620331311520-246422ff83f9?q=80&w=400'
    }
  },
  {
    id: '3',
    userId: 'u3',
    bio: 'Braid master from Port Harcourt. Detailed work and friendly service.',
    categories: ['Braiders'],
    yearsExperience: 7,
    serviceMode: 'both',
    address: 'GRA Phase 2, Port Harcourt',
    latitude: 4.8156,
    longitude: 7.0498,
    avgRating: 4.7,
    totalReviews: 89,
    isAvailable: true,
    user: {
      id: 'u3',
      fullName: 'Amarachi Jumbo',
      email: 'amarachi@example.com',
      phone: '08033344455',
      role: 'professional',
      isVerified: true,
      verificationStatus: 'verified',
      createdAt: new Date(),
      updatedAt: new Date(),
      avatarUrl: 'https://images.unsplash.com/photo-1589156280159-27698a70f29b?q=80&w=400'
    }
  },
  {
    id: '4',
    userId: 'u4',
    bio: 'Executive grooming and premium haircuts. Dedicated studio in Abuja.',
    categories: ['Barbers', 'Grooming'],
    yearsExperience: 10,
    serviceMode: 'shop',
    address: 'Maitama, Abuja',
    latitude: 9.0579,
    longitude: 7.4951,
    avgRating: 5.0,
    totalReviews: 210,
    isAvailable: true,
    accountNumber: '0987654321',
    bankName: 'ZENITH BANK',
    user: {
      id: 'u4',
      fullName: 'Yusuf Ahmed',
      email: 'yusuf@example.com',
      phone: '08055566677',
      role: 'professional',
      isVerified: true,
      verificationStatus: 'verified',
      createdAt: new Date(),
      updatedAt: new Date(),
      avatarUrl: 'https://images.unsplash.com/photo-1503910358245-42d57b39b173?q=80&w=400'
    }
  },
  {
    id: '7',
    userId: 'u7',
    bio: 'Specialist in skin fades and creative hair designs. National award winner.',
    categories: ['Barbers'],
    yearsExperience: 8,
    serviceMode: 'both',
    address: 'Ikoyi, Lagos',
    latitude: 6.4550,
    longitude: 3.4350,
    avgRating: 4.9,
    totalReviews: 167,
    isAvailable: true,
    accountNumber: '1122334455',
    bankName: 'ACCESS BANK',
    user: {
      id: 'u7',
      fullName: 'David Okoro',
      email: 'david@example.com',
      phone: '08133344455',
      role: 'professional',
      isVerified: true,
      verificationStatus: 'verified',
      createdAt: new Date(),
      updatedAt: new Date(),
      avatarUrl: 'https://images.unsplash.com/photo-1593032465175-481ac7f40197?q=80&w=400'
    }
  },
  {
    id: '8',
    userId: 'u8',
    bio: 'Precision barbering with a focus on modern aesthetic. Expert in Caesar cuts and waves.',
    categories: ['Barbers', 'Grooming'],
    yearsExperience: 6,
    serviceMode: 'both',
    address: 'Victoria Island, Lagos',
    latitude: 6.4281,
    longitude: 3.4219,
    avgRating: 4.7,
    totalReviews: 89,
    isAvailable: true,
    accountNumber: '5544332211',
    bankName: 'UBA',
    user: {
      id: 'u8',
      fullName: 'Emeka Nwosu',
      email: 'emeka@example.com',
      phone: '08155500011',
      role: 'professional',
      isVerified: true,
      verificationStatus: 'verified',
      createdAt: new Date(),
      updatedAt: new Date(),
      avatarUrl: 'https://images.unsplash.com/photo-1567894340349-4c11efdec49b?q=80&w=400'
    }
  },
  {
    id: '9',
    userId: 'u9',
    bio: 'The "Kingsman" of Port Harcourt. Luxury grooming services for the elite.',
    categories: ['Barbers', 'Grooming'],
    yearsExperience: 12,
    serviceMode: 'shop',
    address: 'GRA Phase 2, Port Harcourt',
    latitude: 4.8156,
    longitude: 7.0498,
    avgRating: 4.9,
    totalReviews: 312,
    isAvailable: true,
    hasOffer: true,
    accountNumber: '9988776655',
    bankName: 'FIRST BANK',
    user: {
      id: 'u9',
      fullName: 'Samuel Peters',
      email: 'sam@example.com',
      phone: '08122233344',
      role: 'professional',
      isVerified: true,
      verificationStatus: 'verified',
      createdAt: new Date(),
      updatedAt: new Date(),
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400'
    }
  },
  {
    id: '18',
    userId: 'u18',
    bio: 'Luxury barbershop experience. We focus on detail and relaxation in the heart of Abuja.',
    categories: ['Barbers', 'Grooming'],
    yearsExperience: 10,
    serviceMode: 'shop',
    address: 'Maitama, Abuja',
    latitude: 9.0700,
    longitude: 7.5000,
    avgRating: 4.9,
    totalReviews: 255,
    isAvailable: true,
    hasOffer: true,
    accountNumber: '1234567890',
    bankName: 'ZENITH BANK',
    user: {
      id: 'u18',
      fullName: 'Abdul Rahman',
      email: 'abdul@example.com',
      phone: '09055443322',
      role: 'professional',
      isVerified: true,
      verificationStatus: 'verified',
      createdAt: new Date(),
      updatedAt: new Date(),
      avatarUrl: 'https://images.unsplash.com/photo-1506794778242-aff80849ba61?q=80&w=400'
    }
  },
  {
    id: '23',
    userId: 'u23',
    bio: 'Barber with an eye for symmetry. Specialist in textured hair and creative shaves.',
    categories: ['Barbers'],
    yearsExperience: 4,
    serviceMode: 'both',
    address: 'Gwarinpa, Abuja',
    latitude: 9.1000,
    longitude: 7.4000,
    avgRating: 4.7,
    totalReviews: 68,
    isAvailable: true,
    hasOffer: true,
    user: {
      id: 'u23',
      fullName: 'Ahmad Usman',
      email: 'ahmad@example.com',
      phone: '08122331122',
      role: 'professional',
      isVerified: true,
      verificationStatus: 'verified',
      createdAt: new Date(),
      updatedAt: new Date(),
      avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7ee504e3a?q=80&w=400'
    }
  }
];

export const MOCK_SERVICES: Service[] = [
  ...Array.from({ length: 30 }).flatMap((_, i) => [
    { id: `s-fade-${i}`, professionalId: `${(i % 9) + 1}`, category: 'mens_hair' as ServiceCategory, name: 'Premium Fade', description: 'Precision fade with luxury finishing.', price: Math.floor(Math.random() * (8000 - 3000) + 3000), durationMinutes: 45, isActive: true },
    { id: `s-beard-${i}`, professionalId: `${(i % 9) + 1}`, category: 'grooming' as ServiceCategory, name: 'Beard Trim', description: 'Sharp shaping and beard oil application.', price: Math.floor(Math.random() * (4000 - 2000) + 2000), durationMinutes: 30, isActive: true },
    { id: `s-wash-${i}`, professionalId: `${(i % 9) + 1}`, category: 'grooming' as ServiceCategory, name: 'Wash & Taper', description: 'Conditioning wash followed by a clean taper.', price: Math.floor(Math.random() * (5000 - 2500) + 2500), durationMinutes: 40, isActive: true }
  ])
];
